/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package principal;

import javax.swing.JFrame;

/**
 *
 * @author manoel.barros
 */
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Telas.TrocaTelas;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
public class Principal extends javax.swing.JFrame {
int x, y, xx,xy;
    /**
     * Creates new form Principal
     */
URL icon;
    Image icontitle;
    public Principal() {
        super("ESCALA CEDENTE");
        icon = this.getClass().getClassLoader().getResource("icons/Pikachu_dormido_PLB.png");
        icontitle = Toolkit.getDefaultToolkit().getImage(icon);
        setIconImage(icontitle);
        initComponents();

        this.btnHome.setSelected(true);
        
        new TrocaTelas(pnlPrincipal, new Telas.Home());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnHome = new rsbuttom.RSButtonMetro();
        btnCadF = new rsbuttom.RSButtonMetro();
        btnGerEsc = new rsbuttom.RSButtonMetro();
        btnFunc = new rsbuttom.RSButtonMetro();
        btnTroca = new rsbuttom.RSButtonMetro();
        jSeparator1 = new javax.swing.JSeparator();
        btnSobre = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        btnMin = new rsbuttom.RSButtonMetro();
        btnExit = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        pnlPrincipal.setBackground(new java.awt.Color(36, 47, 65));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        pnlMenu.setBackground(new java.awt.Color(36, 47, 65));

        btnHome.setBackground(new java.awt.Color(26, 57, 85));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Home_32px_2.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setColorHover(new java.awt.Color(0, 139, 139));
        btnHome.setColorNormal(new java.awt.Color(26, 57, 85));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCadF.setBackground(new java.awt.Color(26, 57, 85));
        btnCadF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Conference_32px_2.png"))); // NOI18N
        btnCadF.setText("Cadastrar Funcionario");
        btnCadF.setColorHover(new java.awt.Color(0, 139, 139));
        btnCadF.setColorNormal(new java.awt.Color(26, 57, 85));
        btnCadF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadFMousePressed(evt);
            }
        });
        btnCadF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFActionPerformed(evt);
            }
        });

        btnGerEsc.setBackground(new java.awt.Color(26, 57, 85));
        btnGerEsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Calendar_24px.png"))); // NOI18N
        btnGerEsc.setText("Gerar Escala");
        btnGerEsc.setColorHover(new java.awt.Color(0, 139, 139));
        btnGerEsc.setColorNormal(new java.awt.Color(26, 57, 85));
        btnGerEsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGerEscMousePressed(evt);
            }
        });
        btnGerEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerEscActionPerformed(evt);
            }
        });

        btnFunc.setBackground(new java.awt.Color(26, 57, 85));
        btnFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Registration_32px_1.png"))); // NOI18N
        btnFunc.setText("Funcionarios");
        btnFunc.setColorHover(new java.awt.Color(0, 139, 139));
        btnFunc.setColorNormal(new java.awt.Color(26, 57, 85));
        btnFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFuncMousePressed(evt);
            }
        });
        btnFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncActionPerformed(evt);
            }
        });

        btnTroca.setBackground(new java.awt.Color(26, 57, 85));
        btnTroca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Direction_32px_1.png"))); // NOI18N
        btnTroca.setText("Solicitar Troca");
        btnTroca.setColorHover(new java.awt.Color(0, 139, 139));
        btnTroca.setColorNormal(new java.awt.Color(26, 57, 85));
        btnTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrocaMousePressed(evt);
            }
        });
        btnTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setAlignmentX(1.5F);
        jSeparator1.setAlignmentY(1.5F);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 30));

        btnSobre.setBackground(new java.awt.Color(26, 57, 85));
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Question_Mark_32px_1.png"))); // NOI18N
        btnSobre.setText("Sobre ");
        btnSobre.setColorHover(new java.awt.Color(0, 139, 139));
        btnSobre.setColorNormal(new java.awt.Color(26, 57, 85));
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSobreMousePressed(evt);
            }
        });
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGerEsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTroca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGerEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(97, 200, 185));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMin.setBackground(new java.awt.Color(97, 200, 185));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/substract.png"))); // NOI18N
        btnMin.setColorNormal(new java.awt.Color(97, 200, 185));
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
        });
        jPanel3.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 0, 52, 40));

        btnExit.setBackground(new java.awt.Color(97, 200, 185));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnExit.setColorHover(new java.awt.Color(255, 0, 0));
        btnExit.setColorNormal(new java.awt.Color(97, 200, 185));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 52, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 71, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new TrocaTelas(pnlPrincipal, new Telas.Home());
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        this.btnHome.setSelected(true);
        this.btnCadF.setSelected(false);
        this.btnGerEsc.setSelected(false);
        this.btnFunc.setSelected(false);
        this.btnTroca.setSelected(false);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnCadFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFActionPerformed
        // TODO add your handling code here:
        new TrocaTelas(pnlPrincipal, new Telas.Cad_Func());
        
    }//GEN-LAST:event_btnCadFActionPerformed

    private void btnCadFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadFMousePressed
        // TODO add your handling code here:
        this.btnHome.setSelected(false);
        this.btnCadF.setSelected(true);
        this.btnGerEsc.setSelected(false);
        this.btnFunc.setSelected(false);
        this.btnTroca.setSelected(false);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnCadFMousePressed

    private void btnGerEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerEscActionPerformed
        // TODO add your handling code here:
        new TrocaTelas(pnlPrincipal, new Telas.Ger_Escala());
        
    }//GEN-LAST:event_btnGerEscActionPerformed

    private void btnGerEscMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerEscMousePressed
        // TODO add your handling code here:
        this.btnHome.setSelected(false);
        this.btnCadF.setSelected(false);
        this.btnGerEsc.setSelected(true);
        this.btnFunc.setSelected(false);
        this.btnTroca.setSelected(false);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnGerEscMousePressed

    private void btnFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncActionPerformed
        // TODO add your handling code here:
         new TrocaTelas(pnlPrincipal, new Telas.Funcionarios());
      
    }//GEN-LAST:event_btnFuncActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void btnTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaActionPerformed
        // TODO add your handling code here:
         new TrocaTelas(pnlPrincipal, new Telas.Troca());
    }//GEN-LAST:event_btnTrocaActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
         setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
      
        int posicion = pnlMenu.getX();
        if(posicion > -1){
        Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        // TODO add your handling code here:
        new TrocaTelas(pnlPrincipal, new Telas.Sobre());
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnFuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncMousePressed
        // TODO add your handling code here:
        this.btnHome.setSelected(false);
        this.btnCadF.setSelected(false);
        this.btnGerEsc.setSelected(false);
        this.btnFunc.setSelected(true);
        this.btnTroca.setSelected(false);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnFuncMousePressed

    private void btnTrocaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrocaMousePressed
        // TODO add your handling code here:
        this.btnHome.setSelected(false);
        this.btnCadF.setSelected(false);
        this.btnGerEsc.setSelected(false);
        this.btnFunc.setSelected(false);
        this.btnTroca.setSelected(true);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnTrocaMousePressed

    private void btnSobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMousePressed
        // TODO add your handling code here:
        this.btnHome.setSelected(false);
        this.btnCadF.setSelected(false);
        this.btnGerEsc.setSelected(false);
        this.btnFunc.setSelected(false);
        this.btnTroca.setSelected(false);
        this.btnSobre.setSelected(true);
    }//GEN-LAST:event_btnSobreMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCadF;
    private rsbuttom.RSButtonMetro btnExit;
    private rsbuttom.RSButtonMetro btnFunc;
    private rsbuttom.RSButtonMetro btnGerEsc;
    private rsbuttom.RSButtonMetro btnHome;
    private rsbuttom.RSButtonMetro btnMin;
    private rsbuttom.RSButtonMetro btnSobre;
    private rsbuttom.RSButtonMetro btnTroca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
