/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Telas;

/**
 *
 * @author manoel.barros
 */
public class Funcionarios extends javax.swing.JPanel {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        box3 = new javax.swing.JComboBox();
        box4 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adminsitrar Funcionarios");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 52));

        box3.setBackground(new java.awt.Color(36, 47, 65));
        box3.setForeground(new java.awt.Color(255, 255, 255));
        box3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","06:00 as 12:00", "07:00 as 13:00", "08:00 as 14:00", "09:00 as 15:00", "10:00 as 16:00",
            "13:00 as 19:00", "14:00 as 20:00", "15:00 as 21:00", "16:00 as 22:00" }));
add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 147, 30));

box4.setBackground(new java.awt.Color(36, 47, 65));
box4.setForeground(new java.awt.Color(255, 255, 255));
box4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","SDO", "SDE", "SDG", "Contigente", "Supervisor" }));
add(box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 147, 30));

jTable1.setAutoCreateRowSorter(true);
jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
    },
    new String [] {
        "Nome", "Horario", "Cargo", "Ferias"
    }
    ));
    jTable1.setGridColor(new java.awt.Color(255, 255, 255));
    jScrollPane2.setViewportView(jTable1);

    add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 380, 350));

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Contacts_32px_2.png"))); // NOI18N
    jLabel3.setText("Nome:");
    add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Clock_32px_2.png"))); // NOI18N
    jLabel4.setText("Horario:");
    add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Anonymous_Mask_32px_1.png"))); // NOI18N
    jLabel6.setText("Ferias:");
    add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Conference_32px_2.png"))); // NOI18N
    jLabel1.setText("Cargo:");
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

    jTextField1.setBackground(new java.awt.Color(36, 47, 65));
    jTextField1.setForeground(new java.awt.Color(255, 255, 255));
    add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 150, 30));

    jTextField2.setBackground(new java.awt.Color(36, 47, 65));
    jTextField2.setForeground(new java.awt.Color(255, 255, 255));
    add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 30));

    rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/32x32/icons8_Registration_32px_1.png"))); // NOI18N
    rSButtonMetro1.setText("Alterar");
    rSButtonMetro1.setColorHover(new java.awt.Color(0, 204, 0));
    add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box3;
    private javax.swing.JComboBox box4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables
}
